import type { CartItem, PurchasedAsset, ResaleQuote } from "./types";

export const purchasedAssets: PurchasedAsset[] = [
  {
    id: "iqoo-pad2-pro",
    category: "tablet",
    brand: "iQOO",
    model: "iQOO Pad2 Pro",
    storage: "12GB+256GB",
    color: "星云灰",
    purchasedAt: "2024-05-31",
    paidPrice: 3499,
    status: "active",
    ecosystem: "vivo-iqoo",
    estimateMin: 1180,
    estimateMax: 1380,
    forecast90: 1200,
    image: "./assets/iqoo-pad2-pro.png",
  },
  {
    id: "iqoo-pad-air",
    category: "tablet",
    brand: "iQOO",
    model: "iQOO Pad Air",
    storage: "8GB+256GB",
    color: "星钻白",
    purchasedAt: "2023-09-15",
    paidPrice: 2499,
    status: "active",
    ecosystem: "vivo-iqoo",
    estimateMin: 620,
    estimateMax: 780,
    forecast90: 680,
  },
  {
    id: "vivo-pad3-pro",
    category: "tablet",
    brand: "vivo",
    model: "vivo Pad3 Pro",
    storage: "12GB+256GB",
    color: "寒星灰",
    purchasedAt: "2024-04-08",
    paidPrice: 3299,
    status: "active",
    ecosystem: "vivo-iqoo",
    estimateMin: 1080,
    estimateMax: 1280,
    forecast90: 1110,
  },
];

export const cartItems: CartItem[] = [
  {
    id: "iqoo-pad6-pro",
    category: "tablet",
    title: "iQOO Pad6 Pro",
    spec: "灰晶｜12GB+256GB｜Wi-Fi版",
    price: 3899,
    quantity: 1,
    selected: true,
    ecosystem: "vivo-iqoo",
    image: "./assets/iqoo-pad6-pro.png",
  },
  {
    id: "iqoo-keyboard",
    category: "accessory",
    title: "iQOO 智能触控键盘",
    spec: "黑色｜适配 iQOO Pad6 Pro",
    price: 599,
    quantity: 1,
    selected: true,
    ecosystem: "vivo-iqoo",
    image: "./assets/iqoo-keyboard.png",
  },
];

export const demoQuote: ResaleQuote = {
  assetId: "iqoo-pad2-pro",
  estimateMin: 1180,
  estimateMax: 1380,
  forecast30: 1320,
  forecast90: 1200,
  tradeInBonus: 200,
  confidence: "medium",
  asOf: "2026-06-29",
};
