import type { CartItem, PurchasedAsset } from "./types";

export const TRADE_IN_BONUS = 200;

export const purchasedAssets: PurchasedAsset[] = [
  {
    id: "iqoo-pad2-pro",
    category: "tablet",
    brand: "iQOO",
    model: "iQOO Pad2 Pro",
    storage: "12GB+256GB",
    color: "星云灰",
    purchasedAt: "2024-05-31",
    paidPrice: 3499,
    status: "active",
    ecosystem: "vivo-iqoo",
    estimateMin: 1180,
    estimateMax: 1380,
    forecast30: 1320,
    forecast60: 1260,
    forecast90: 1200,
    image: "./assets/iqoo-pad2-pro.png",
  },
  {
    id: "iqoo-11-phone",
    category: "phone",
    brand: "iQOO",
    model: "iQOO 11",
    storage: "12GB+256GB",
    color: "赛道版",
    purchasedAt: "2023-02-18",
    paidPrice: 4399,
    status: "active",
    ecosystem: "vivo-iqoo",
    estimateMin: 620,
    estimateMax: 760,
    forecast30: 710,
    forecast60: 660,
    forecast90: 610,
    image: "./assets/iqoo-11-phone.png",
  },
  {
    id: "vivo-tws4",
    category: "earbuds",
    brand: "vivo",
    model: "vivo TWS 4",
    storage: "标准版",
    color: "千峰白",
    purchasedAt: "2024-04-03",
    paidPrice: 399,
    status: "active",
    ecosystem: "vivo-iqoo",
    estimateMin: 120,
    estimateMax: 180,
    forecast30: 160,
    forecast60: 145,
    forecast90: 130,
    image: "./assets/vivo-tws4.png",
  },
  {
    id: "vivo-pad3-pro",
    category: "tablet",
    brand: "vivo",
    model: "vivo Pad3 Pro",
    storage: "12GB+256GB",
    color: "寒星灰",
    purchasedAt: "2024-04-08",
    paidPrice: 3299,
    status: "active",
    ecosystem: "vivo-iqoo",
    estimateMin: 1080,
    estimateMax: 1280,
    forecast30: 1220,
    forecast60: 1160,
    forecast90: 1110,
    image: "./assets/vivo-pad3-pro.png",
  },
];

export const cartItems: CartItem[] = [
  {
    id: "iqoo-pad6-pro",
    category: "tablet",
    title: "iQOO Pad6 Pro",
    spec: "灰晶｜12GB+256GB｜Wi-Fi版",
    price: 3899,
    quantity: 1,
    selected: true,
    ecosystem: "vivo-iqoo",
    image: "./assets/iqoo-pad6-pro.png",
  },
  {
    id: "iqoo-keyboard",
    category: "accessory",
    title: "iQOO 智能触控键盘",
    spec: "黑色｜适配 iQOO Pad6 Pro",
    price: 599,
    quantity: 1,
    selected: true,
    ecosystem: "vivo-iqoo",
    image: "./assets/iqoo-keyboard.png",
  },
];
